Repository ant-design/ant-design-charts, pull requests merged in 2025-09, with the labels that each got.

#3059 feat: add plugins configuration
  packages/plots/src/core/constants/index.ts
  site/.dumi/global.ts
  site/examples/statistics/line/demo/meta.json
  site/examples/statistics/line/demo/sketchy.js
  site/package.json
Labels: feature 💡, size:M

#3060 chore: change log
  packages/charts/CHANGELOG.md
  packages/charts/package.json
  packages/plots/CHANGELOG.md
  packages/plots/package.json
Labels: size:M

#3061 docs: add grouped stacked column line demo
  site/examples/statistics/dual-axes/demo/grouped-stacked-column-line.js
  site/examples/statistics/dual-axes/demo/meta.json
Labels: plots, size:M, lgtm

#3065 fix(annotation): update logic
  packages/plots/src/core/annotation/bidirectional-bar-axis-text.ts
  packages/plots/src/core/annotation/conversion-tag.ts
  packages/plots/src/core/annotation/core.ts
  packages/plots/src/core/base/index.ts
Labels: bug 🐛, plots, size:M, lgtm

#3068 docs: add quadrants example
  site/examples/case/interactions/demo/meta.json
  site/examples/case/interactions/demo/quadrants.js
  site/examples/statistics/annotation-shape/demo/line.js
  site/examples/statistics/annotation-shape/demo/meta.json
Labels: plots, documentation 📖, size:L, lgtm
